;;===============================
;; Name:HONGRUI ZHENG
;;===============================

.orig x3000

	;INITIALIZE STACK
	LD R6, STACK
	;CALL MC91(N)
	LD R0, N
	ADD R6, R6, -1
	STR R0, R6, 0   ; PUSH ARGUMENT INTO FIRST STACK
	JSR MC91
	;POP RETURN VALUE AND ARG OFF STACK
	LDR R0, R6, 0
	ADD R6, R6, 2
	;SAVE THE ANSWER
	ST R0, ANSWER
	HALT

STACK	.fill xF000
N	.fill 99       ;input n
ANSWER	.blkw 1    ;save your answer here

MC91
	ADD R6, R6, -3 ;POINTS R6 TO OLD FP
	STR R7, R6, 1  ;STORE RETURN ADDRESS
	STR R5, R6, 0  ;STORE OLD FP INTO STACK
	ADD R5, R6, -1 ;CREATE NEW FP WILL POINT ONE ABOVE OLD FP


	;ADD R6, R6, -2 ;MAKE ROOM FOR LOCAL VARIABLES


	LDR R0, R5, 4  ;R0 = N
	ADD R2, R0, -15
	ADD R2, R0, -15
	ADD R2, R0, -15
	ADD R2, R0, -15
	ADD R2, R0, -15
	ADD R2, R0, -15
	ADD R2, R0, -10 ;CHECK IF N IS GREATER THAN 100
	BRp RETURNMINUSTEN
	ADD R0, R0, 11  ;N+11
	ADD R6, R6, -1 
	STR R0, R6, 0   ;PUSH INTO ARGUMENT FOR NEW STACK
	JSR MC91		
	JSR MC91		;CALL M(M(N+11))
	BR RETURN


RETURNMINUSTEN
	ADD R0, R0, -10 ;N-10
	BR RETURN

RETURN
	ADD R6, R5, 0 ; POINT SP TO FP
	STR R0, R5, 3 ;	STORE RETURN VALUE
	LDR R7, R5, 2 ; RESTORE RETURN ADDRESS
	LDR R5, R5, 1 ; POINT R5 TO OLD FP
	ADD R6, R6, 3 ; POINT SP TO RETURN VALUE RETURN ADDRESS
	RET

.end
